-- ============================================================================
-- 010 — توثيق المخطط الحي: الجداول الـ ١٨ التي كانت تعيش في لوحة Supabase فقط
-- ============================================================================
--
-- المشكلة التي يحلّها هذا الملف:
-- كود المنصة يستعمل ٢٢ جدولاً، والترحيلات ٠٠١–٠٠٩ تنشئ أربعة منها فقط
-- (whatsapp_messages, merchants, couriers, shipments) وتضيف conversations و
-- messages. البقية أُنشئت يدوياً في لوحة Supabase ولم تُسجَّل في المستودع.
--
-- أثر ذلك عملياً:
--   • لا يمكن إنشاء بيئة اختبار أو تطوير مطابقة — أي مطوّر جديد يواجه
--     قاعدة ناقصة ومسارات تنهار بأخطاء "relation does not exist".
--   • لا استرجاع بعد خطأ: لا يوجد تعريف مرجعي يُعاد منه البناء.
--   • لا مراجعة على تغييرات المخطط: تعديل عمود مالي في اللوحة لا يمرّ بأي
--     مراجعة ولا يترك أثراً في تاريخ المستودع.
--   • مخالفة صريحة لبند ٢-ب (الهندسة أولاً) في CLAUDE.md.
--
-- طريقة التوليد: كل سطر هنا مُستخرَج من قاعدة البيانات الحية بالاستعلام عن
-- pg_catalog بتاريخ ٢٠٢٦-٠٩-١٥ — لا عمود ولا قيد ولا فهرس مكتوب من الذاكرة
-- أو مُخمَّن (بند ٢-أ، انعدام التخمين).
--
-- آمن للتشغيل على القاعدة الحية: كل شيء if not exists / or replace، ولا
-- يحذف ولا يغيّر أي بيانات قائمة. الغرض منه أن يصبح المستودع مصدر الحقيقة
-- للمخطط ابتداءً من اليوم.
--
-- ⚠️ ملاحظة درفت مرصودة: الترحيل ٠٠٢ يعرّف shipments.merchant_net_amount_iqd
-- بقيمة default، بينما العمود في القاعدة الحية GENERATED ALWAYS STORED.
-- النسخة الحية هي الصحيحة (الصافي يُشتق ولا يُخزَّن مُخمَّناً — بند ٤-٤)،
-- وهي المثبَّتة أدناه في القسم ٤.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) الطلبات وعناصرها
-- ----------------------------------------------------------------------------

create table if not exists public.orders (
  order_id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  phone_number text not null,
  name text,
  address text,
  phone text,
  current_state text,
  address_details text,
  governorate text,
  district text,
  contact_phone text,
  items_total_iqd numeric,
  delivery_fee_iqd numeric,
  grand_total_iqd numeric,
  updated_at timestamptz,
  customer_name text,
  order_content text,
  order_book_id uuid
);

comment on table public.orders is
  'الطلبات الواردة من البوت ومن لوحة التحكم. لا تحمل merchant_id — نسبة الطلب للتاجر تتم عبر الشحنة المرتبطة (shipments.merchant_id).';
comment on column public.orders.items_total_iqd is 'ثمن البضاعة المُحصَّل من الزبون (COD) — منفصل عن أجرة التوصيل، بند ٤-٤.';
comment on column public.orders.delivery_fee_iqd is 'أجرة التوصيل — لا تُدمج في ثمن البضاعة ولا تُشتق منه.';

create index if not exists orders_phone_number_idx on public.orders (phone_number);
create index if not exists orders_phone_created_idx on public.orders (phone_number, created_at desc);
create index if not exists orders_order_book_idx on public.orders (order_book_id);

create table if not exists public.order_items (
  id bigint generated always as identity primary key,
  order_id bigint references public.orders (order_id) on delete cascade,
  variant_id text,
  product_name_snapshot text,
  color_snapshot text,
  size_snapshot text,
  quantity integer default 1,
  unit_price_iqd numeric default 0,
  created_at timestamptz default now()
);

comment on table public.order_items is
  'عناصر الطلب بلقطة (snapshot) من بيانات المنتج وقت الطلب — تغيّر سعر المنتج لاحقاً لا يعيد كتابة تاريخ الطلب.';

-- ----------------------------------------------------------------------------
-- 2) الباقات والاشتراكات
-- ----------------------------------------------------------------------------

create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name_en text not null,
  tagline_ar text not null,
  price_iqd_monthly bigint check (price_iqd_monthly is null or price_iqd_monthly >= 0),
  list_price_iqd_monthly bigint check (list_price_iqd_monthly is null or list_price_iqd_monthly >= 0),
  sort_order integer not null,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  max_social_accounts integer not null,
  max_ai_agents integer not null,
  max_actions_monthly integer not null,
  max_catalogs integer not null,
  max_products integer not null,
  max_order_books integer not null,
  max_team_seats integer not null,
  analytics_tier text not null check (analytics_tier in ('basic', 'advanced')),
  support_tier text not null check (support_tier in ('standard', 'priority', 'vip')),
  has_api_access boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.plans is 'باقات اشتراك منصة برق. الأسعار بالدينار العراقي.';
comment on column public.plans.price_iqd_monthly is
  'null = السعر لم يُعتمد بعد. الواجهة تعرض "قريباً" بدل رقم مُخمَّن.';

create index if not exists plans_active_sort_idx on public.plans (sort_order) where is_active;

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  plan_id uuid not null references public.plans (id),
  status text not null default 'trialing'
    check (status in ('trialing', 'active', 'past_due', 'canceled')),
  current_period_start timestamptz not null default now(),
  current_period_end timestamptz,
  canceled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.subscriptions is
  'اشتراكات التجار. صف فعّال واحد لكل تاجر (يفرضه الفهرس أدناه)، والملغاة تبقى للسجل المالي.';

-- اشتراكان فعّالان لتاجر واحد يعنيان حدَّي باقة متضاربين وفوترة مزدوجة
create unique index if not exists subscriptions_one_live_per_merchant
  on public.subscriptions (merchant_id)
  where status in ('trialing', 'active', 'past_due');

create index if not exists subscriptions_plan_idx on public.subscriptions (plan_id);

-- ----------------------------------------------------------------------------
-- 3) الكتالوج والمنتجات والكوبونات
-- ----------------------------------------------------------------------------

create table if not exists public.catalogs (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (merchant_id, name)
);

create index if not exists catalogs_merchant_idx on public.catalogs (merchant_id);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  color text,
  size text,
  price text,
  stock integer,
  status text,
  price_iqd numeric,
  merchant_id uuid references public.merchants (id) on delete cascade,
  catalog_id uuid references public.catalogs (id) on delete set null
);

comment on column public.products.price is
  'عمود نصي قديم من أيام الإدخال اليدوي. السعر المعتمد للحساب هو price_iqd الرقمي.';

create index if not exists products_merchant_idx on public.products (merchant_id);
create index if not exists products_catalog_idx on public.products (catalog_id);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  code text not null,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  discount_value numeric not null check (discount_value >= 0),
  min_order_iqd numeric not null default 0 check (min_order_iqd >= 0),
  max_uses integer check (max_uses is null or max_uses > 0),
  used_count integer not null default 0 check (used_count >= 0),
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (merchant_id, code),
  -- خصم نسبي فوق ١٠٠٪ يعني أن المتجر يدفع للزبون
  constraint coupons_percent_range
    check (discount_type <> 'percent' or discount_value <= 100)
);

comment on table public.coupons is 'أكواد الخصم التي يطبّقها الموظف الذكي داخل المحادثة.';

create index if not exists coupons_merchant_idx on public.coupons (merchant_id) where is_active;

-- ----------------------------------------------------------------------------
-- 4) الموظفون الأذكياء وحسابات التواصل وسجلات الطلبات
-- ----------------------------------------------------------------------------

create table if not exists public.ai_agents (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  name text not null,
  role text,
  system_prompt text,
  catalog_id uuid references public.catalogs (id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_agents_name_unique unique (merchant_id, name)
);

comment on table public.ai_agents is
  'الموظفون الأذكياء: كل صف شخصية بوت بقاعدة معرفتها. يُحدّ عددهم بـ plans.max_ai_agents. ⚠️ لا يوجد في المنصة كود يقرأ system_prompt ويولّد رداً — التوليد يقع خارجها في n8n.';

create index if not exists ai_agents_merchant_idx on public.ai_agents (merchant_id);

create table if not exists public.social_accounts (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  platform text not null check (platform in ('whatsapp', 'instagram', 'messenger')),
  external_id text not null,
  display_name text,
  handle text,
  status text not null default 'connected'
    check (status in ('connected', 'needs_reauth', 'disconnected')),
  ai_agent_id uuid references public.ai_agents (id) on delete set null,
  connected_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- حساب واحد لا يُربط بتاجرين: وإلا وصلت رسائل الزبون لمتجرين
  constraint social_accounts_external_unique unique (platform, external_id)
);

create index if not exists social_accounts_merchant_idx on public.social_accounts (merchant_id);
create index if not exists social_accounts_agent_idx on public.social_accounts (ai_agent_id);

create table if not exists public.order_books (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_books_name_unique unique (merchant_id, name)
);

comment on table public.order_books is
  'سجلات الطلبات: خط استقبال مستقل (فرع أو نشاط منفصل). يُحدّ بـ plans.max_order_books.';

create index if not exists order_books_merchant_idx on public.order_books (merchant_id);

-- سجل افتراضي واحد لكل تاجر — اثنان يجعلان وجهة الطلب الجديد غير محدَّدة
create unique index if not exists order_books_one_default_idx
  on public.order_books (merchant_id) where is_default;

-- ----------------------------------------------------------------------------
-- 5) ملفّات التاجر وإعدادات التوصيل
-- ----------------------------------------------------------------------------

create table if not exists public.merchant_profiles (
  merchant_id uuid primary key references public.merchants (id) on delete cascade,
  about text,
  working_hours text,
  contact_phone text,
  address text,
  maps_url text,
  delivery_zone text,
  current_offers text,
  updated_at timestamptz not null default now()
);

comment on table public.merchant_profiles is
  'تفاصيل النشاط التي يشاركها الموظف الذكي مع الزبائن — الدوام والموقع والعروض.';

create table if not exists public.merchant_delivery_settings (
  merchant_id uuid primary key references public.merchants (id) on delete cascade,
  base_governorate text not null default 'بغداد',
  local_fee_iqd bigint not null default 0 check (local_fee_iqd >= 0),
  local_days integer not null default 1 check (local_days >= 0),
  local_note text,
  other_fee_iqd bigint not null default 0 check (other_fee_iqd >= 0),
  other_days integer not null default 2 check (other_days >= 0),
  other_note text,
  updated_at timestamptz not null default now()
);

comment on table public.merchant_delivery_settings is
  'قواعد التوصيل التي يعلنها التاجر ويجيب بها الموظف الذكي. تختلف عن delivery_areas التي هي تسعيرة برق الداخلية.';

create table if not exists public.delivery_areas (
  id bigint generated always as identity primary key,
  area_name text not null,
  governorate text not null,
  delivery_fee_iqd integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint delivery_areas_unique unique (area_name, governorate)
);

comment on table public.delivery_areas is
  'دليل مناطق التوصيل. يميّز الأسماء المتشابهة بين المحافظات (العامرية في بغداد وفي الأنبار) قبل تثبيت العنوان — بند ٤-٣.';

create index if not exists delivery_areas_name_idx on public.delivery_areas (area_name);

-- ----------------------------------------------------------------------------
-- 6) المروّجون والحملات الإعلانية
-- ----------------------------------------------------------------------------

create table if not exists public.marketers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  agency_name text,
  email text,
  phone text,
  status text not null default 'active' check (status in ('active', 'suspended')),
  commission_rate numeric
    check (commission_rate is null or (commission_rate >= 0 and commission_rate <= 100)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketer_merchants (
  marketer_id uuid not null references public.marketers (id) on delete cascade,
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (marketer_id, merchant_id)
);

create index if not exists marketer_merchants_merchant_idx
  on public.marketer_merchants (merchant_id);

create table if not exists public.ad_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  merchant_id uuid not null references public.merchants (id) on delete cascade,
  marketer_id uuid references public.marketers (id) on delete set null,
  platform text not null
    check (platform in ('instagram', 'facebook', 'tiktok', 'snapchat', 'google')),
  status text not null default 'under_review'
    check (status in ('active', 'completed', 'under_review', 'paused')),
  budget_total_iqd bigint not null default 0 check (budget_total_iqd >= 0),
  budget_spent_iqd bigint not null default 0 check (budget_spent_iqd >= 0),
  daily_budget_iqd bigint not null default 0 check (daily_budget_iqd >= 0),
  attributed_revenue_iqd bigint not null default 0 check (attributed_revenue_iqd >= 0),
  reach integer not null default 0 check (reach >= 0),
  impressions integer not null default 0 check (impressions >= 0),
  clicks integer not null default 0 check (clicks >= 0),
  conversions integer not null default 0 check (conversions >= 0),
  start_date date,
  end_date date,
  target_audience text,
  ad_headline text,
  marketer_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- العائد على الإنفاق محسوب لا مخزَّن: رقم يُكتب يدوياً يفترق عن مكوّناته
  roas numeric generated always as (
    case when budget_spent_iqd > 0
      then round(attributed_revenue_iqd::numeric / budget_spent_iqd::numeric, 2)
      else null
    end
  ) stored,
  -- قمع التحويل لا ينقلب: نقرات أكثر من الظهور أو تحويلات أكثر من النقرات
  -- تعني بيانات مُدخلة خطأً، وقرار ميزانية مبني عليها قرار خاطئ
  constraint ad_campaigns_funnel_order check (clicks <= impressions),
  constraint ad_campaigns_conversions_order check (conversions <= clicks),
  constraint ad_campaigns_date_order
    check (start_date is null or end_date is null or end_date >= start_date)
);

create index if not exists ad_campaigns_merchant_idx on public.ad_campaigns (merchant_id);
create index if not exists ad_campaigns_marketer_idx on public.ad_campaigns (marketer_id);
create index if not exists ad_campaigns_status_idx on public.ad_campaigns (status);

-- ----------------------------------------------------------------------------
-- 7) جلسات الزبائن وملفّات المستخدمين
-- ----------------------------------------------------------------------------

create table if not exists public.customer_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id text,
  debounce_token text,
  last_message_at timestamptz,
  last_customer_message_at timestamptz,
  updated_at timestamptz,
  phone_number text unique,
  human_takeover boolean default false,
  last_reply_at timestamptz,
  stage text not null default '0',
  session_data jsonb default '{}'::jsonb,
  is_processing boolean not null default false,
  platform text,
  bot_active boolean default true
);

comment on table public.customer_sessions is
  'حالة جلسة البوت لكل رقم زبون — يكتبها مسار n8n. مصدر الحقيقة للمحادثة نفسها هو conversations/messages.';

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users (id) on delete cascade,
  store_name text,
  phone text,
  default_currency text not null default 'IQD',
  role text not null default 'employee',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  merchant_id uuid references public.merchants (id) on delete set null
);

comment on table public.profiles is
  'ربط مستخدم auth.users بتاجر ودور. ⚠️ الجدول موجود والمنصة لا تستعمله بعد: لا يوجد تسجيل دخول، وكل مسار يعمل بـ service_role. هذا الجدول هو نقطة البدء عند بناء المصادقة — عندها تُشتق merchant_id من الجلسة لا من الرابط.';

create index if not exists profiles_merchant_idx on public.profiles (merchant_id);

-- ----------------------------------------------------------------------------
-- 8) فرض حدود الباقة في قاعدة البيانات
--
-- الفرض هنا لا في الكود: مسار كتابة واحد يُنسى فيه الفحص يكفي لتجاوز الحدّ.
-- الدالة SECURITY DEFINER لأن الفحص يقرأ subscriptions و plans، وقد لا يملك
-- الدور المُنفِّذ صلاحية عليهما.
--
-- رموز الخطأ مُلتقَطة في lib/plan-limits.ts وتُترجم إلى ردود HTTP عربية:
--   BQ001 = تجاوز الحدّ (409)، BQ002 = لا اشتراك فعّال (402).
-- الرسالة تُرسَل وسوماً خاماً (BQ_LIMIT|التسمية|الحدّ) لا جملة جاهزة، لأن
-- قاعدة البيانات لا تعرف أن الواجهة تعرض أرقاماً عربية.
-- ----------------------------------------------------------------------------

create or replace function public.enforce_plan_limit()
returns trigger
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_limit_column text := TG_ARGV[0];
  v_label        text := TG_ARGV[1];
  v_limit        int;
  v_count        int;
begin
  if NEW.merchant_id is null then
    return NEW;
  end if;

  -- قفل صف التاجر يُسلسل الإدخالات المتزامنة، فلا يمرّ طلبان معاً عند الحدّ
  perform 1 from public.merchants where id = NEW.merchant_id for update;

  execute format(
    'select p.%I
       from public.subscriptions s
       join public.plans p on p.id = s.plan_id
      where s.merchant_id = $1
        and s.status in (''trialing'',''active'',''past_due'')
      order by s.current_period_start desc
      limit 1',
    v_limit_column
  ) into v_limit using NEW.merchant_id;

  if v_limit is null then
    raise exception 'BQ_NO_SUBSCRIPTION|%', v_label using errcode = 'BQ002';
  end if;

  execute format('select count(*) from public.%I where merchant_id = $1', TG_TABLE_NAME)
    into v_count using NEW.merchant_id;

  if v_count >= v_limit then
    raise exception 'BQ_LIMIT|%|%', v_label, v_limit using errcode = 'BQ001';
  end if;

  return NEW;
end;
$function$;

revoke execute on function public.enforce_plan_limit() from public;
revoke execute on function public.enforce_plan_limit() from anon;
revoke execute on function public.enforce_plan_limit() from authenticated;

drop trigger if exists ai_agents_plan_limit on public.ai_agents;
create trigger ai_agents_plan_limit
  before insert on public.ai_agents
  for each row execute function public.enforce_plan_limit('max_ai_agents', 'موظف ذكي');

drop trigger if exists catalogs_plan_limit on public.catalogs;
create trigger catalogs_plan_limit
  before insert on public.catalogs
  for each row execute function public.enforce_plan_limit('max_catalogs', 'قاعدة منتجات');

drop trigger if exists order_books_plan_limit on public.order_books;
create trigger order_books_plan_limit
  before insert on public.order_books
  for each row execute function public.enforce_plan_limit('max_order_books', 'سجل طلبات');

drop trigger if exists products_plan_limit on public.products;
create trigger products_plan_limit
  before insert on public.products
  for each row execute function public.enforce_plan_limit('max_products', 'منتج');

drop trigger if exists social_accounts_plan_limit on public.social_accounts;
create trigger social_accounts_plan_limit
  before insert on public.social_accounts
  for each row execute function public.enforce_plan_limit('max_social_accounts', 'حساب تواصل');

-- ----------------------------------------------------------------------------
-- 9) أمان الصفوف
--
-- كل جدول هنا يحمل بيانات تاجر أو زبون. RLS مفعَّلة بلا policy لـ anon و
-- authenticated ⇒ رفض افتراضي تام، وservice_role وحده يتجاوزها (وهو ما
-- تستعمله مسارات الخادم و n8n).
--
-- ⚠️ هذا ليس عزلاً بين التجار. اليوم كل مسار في المنصة يعمل بـ service_role
-- ويأخذ merchant_id من الرابط، فلا شيء يمنع تاجراً من قراءة بيانات آخر.
-- العزل الحقيقي يبدأ عند بناء المصادقة: تُضاف عندها policies تشتقّ التاجر من
-- الجلسة عبر public.profiles، مثال:
--
--   create policy catalogs_own on public.catalogs for select to authenticated
--     using (merchant_id = (select merchant_id from public.profiles
--                            where user_id = auth.uid()));
-- ----------------------------------------------------------------------------

alter table public.orders                     enable row level security;
alter table public.order_items                enable row level security;
alter table public.plans                      enable row level security;
alter table public.subscriptions              enable row level security;
alter table public.catalogs                   enable row level security;
alter table public.products                   enable row level security;
alter table public.coupons                    enable row level security;
alter table public.ai_agents                  enable row level security;
alter table public.social_accounts            enable row level security;
alter table public.order_books                enable row level security;
alter table public.merchant_profiles          enable row level security;
alter table public.merchant_delivery_settings enable row level security;
alter table public.delivery_areas             enable row level security;
alter table public.marketers                  enable row level security;
alter table public.marketer_merchants         enable row level security;
alter table public.ad_campaigns               enable row level security;
alter table public.customer_sessions          enable row level security;
alter table public.profiles                   enable row level security;
